-- Bảng SUPPLIER
CREATE TABLE SUPPLIER (
    SUPPLIER_ID INT IDENTITY(1,1) PRIMARY KEY,
    SUPPLIER_NAME VARCHAR(30),
    SUPPLIER_EMAIL VARCHAR(30),
    SUPPLIER_PHONE VARCHAR(20),
    ADDRESS VARCHAR(100)
);

-- Bảng PRODUCT
CREATE TABLE PRODUCT (
    PRODUCT_ID INT IDENTITY(1,1) PRIMARY KEY,
    PRODUCT_NAME VARCHAR(30),
    BRAND VARCHAR(30),
    STYLE_TAG VARCHAR(30),
    SEASON VARCHAR(30),
    CATEGORY VARCHAR(30),
    DESCRIPTION TEXT
);




-- Bảng ITEM
CREATE TABLE ITEM (
    ITEM_ID INT IDENTITY(1,1) PRIMARY KEY,
    IMPORT_PRICE DECIMAL(10, 2),
    SELLING_PRICE DECIMAL(10, 2),
    SIZE VARCHAR(10),
    COLOR VARCHAR(10),
    STOCK INT,
    PRODUCT_ID INT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

-- Bảng IMPORT_BILL
CREATE TABLE IMPORT_BILL (
    IMPORT_ID INT IDENTITY(1,1) PRIMARY KEY,
    IMPORT_STATE VARCHAR(30),
    TOTAL_FEE DECIMAL(10, 2)
);

-- Bảng IMPORT
CREATE TABLE IMPORT (
    IMPORT_ID INT,
    ITEM_ID INT,
    SUPPLIER_ID INT,
    IMPORT_QUANTITY INT,
    FOREIGN KEY (IMPORT_ID) REFERENCES IMPORT_BILL(IMPORT_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID),
    PRIMARY KEY (IMPORT_ID, ITEM_ID)
);

-- Bảng RETURN_BILL
CREATE TABLE RETURN_BILL (
    RETURN_ID INT IDENTITY(1,1) PRIMARY KEY,
    REASON TEXT,
    REFUND_FEE DECIMAL(10, 2)
);

-- Bảng RETURN_ITEM
CREATE TABLE RETURN_ITEM (
    RETURN_ID INT,
    ITEM_ID INT,
    SUPPLIER_ID INT,
    RETURN_QUANTITY INT,
    FOREIGN KEY (RETURN_ID) REFERENCES RETURN_BILL(RETURN_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID),
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID),
    PRIMARY KEY (RETURN_ID, ITEM_ID)
);

-- Bảng RECONCILIATION_FORM
CREATE TABLE RECONCILIATION_FORM (
    CHECK_ID INT IDENTITY(1,1) PRIMARY KEY,
    CHECKED_DATE DATE
);

-- Bảng RECONCILE
CREATE TABLE RECONCILE (
    CHECK_ID INT,
    ITEM_ID INT,
    ID_CARD_NUM VARCHAR(30),
    ACTUAL_QUANTITY INT,
    FOREIGN KEY (CHECK_ID) REFERENCES RECONCILIATION_FORM(CHECK_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID),
    PRIMARY KEY (CHECK_ID, ITEM_ID)
);

-- Bảng PRODUCT_SET
CREATE TABLE PRODUCT_SET (
    SET_ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(100),
    STYLE VARCHAR(50)
);

-- Bảng COMBINE
CREATE TABLE COMBINE (
    PRODUCT_ID INT,
    SET_ID INT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    FOREIGN KEY (SET_ID) REFERENCES PRODUCT_SET(SET_ID),
    PRIMARY KEY (PRODUCT_ID, SET_ID)
);

-- Xóa các bảng con trước
DROP TABLE IF EXISTS RECONCILE;
DROP TABLE IF EXISTS IMPORT;
DROP TABLE IF EXISTS RETURN_ITEM;
DROP TABLE IF EXISTS COMBINE;

-- Xóa các bảng cha
DROP TABLE IF EXISTS RECONCILIATION_FORM;
DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS PRODUCT_SET;
DROP TABLE IF EXISTS RETURN_BILL;
DROP TABLE IF EXISTS IMPORT_BILL;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS SUPPLIER;
