-- DROP các ràng buộc foreign key
-- Drop Foreign Keys
ALTER TABLE INCHARGE_OF DROP CONSTRAINT fk_incharge_of_vs_order;
ALTER TABLE INCHARGE_OF DROP CONSTRAINT fk_incharge_of_vs_sales_employee;

ALTER TABLE PREPARE DROP CONSTRAINT fk_prepare_vs_order;
ALTER TABLE PREPARE DROP CONSTRAINT fk_prepare_vs_packaging_employee;

ALTER TABLE GET_FEEDBACK DROP CONSTRAINT fk_get_feedback_vs_order;
ALTER TABLE GET_FEEDBACK DROP CONSTRAINT fk_get_feedback_vs_customer_service_employee;

ALTER TABLE HANDLE DROP CONSTRAINT fk_handle_vs_order;
ALTER TABLE HANDLE DROP CONSTRAINT fk_handle_vs_customer_service_employee;

ALTER TABLE INCLUDE_ITEM DROP CONSTRAINT fk_include_item_vs_order;
ALTER TABLE INCLUDE_ITEM DROP CONSTRAINT fk_include_item_vs_item;

ALTER TABLE VOUCHER_VALID_PERIOD DROP CONSTRAINT fk_voucher_valid_period_vs_voucher;

ALTER TABLE COMBINE DROP CONSTRAINT Fk_Combine_Product;
ALTER TABLE COMBINE DROP CONSTRAINT Fk_Combine_Product_Set;

ALTER TABLE RECONCILE DROP CONSTRAINT FK_Reconcile_Item;
ALTER TABLE RECONCILE DROP CONSTRAINT Fk_Warehouse_Employee_ID;
ALTER TABLE RECONCILE DROP CONSTRAINT Fk_Reconcile_Reconciliation_Form;

ALTER TABLE RETURN_ITEM DROP CONSTRAINT Fk_Return_Item_Item;
ALTER TABLE RETURN_ITEM DROP CONSTRAINT Fk_Return_Item_Suplier;
ALTER TABLE RETURN_ITEM DROP CONSTRAINT Fk_Return_Item_Return_Bill;

ALTER TABLE IMPORT DROP CONSTRAINT Fk_Import_Import_Bill;
ALTER TABLE IMPORT DROP CONSTRAINT Fk_Import_Item;
ALTER TABLE IMPORT DROP CONSTRAINT Fk_Import_Supplier;

ALTER TABLE MANAGE_INCOME DROP CONSTRAINT FK_Of_Group_Voucher;
ALTER TABLE MANAGE_INCOME DROP CONSTRAINT FK_Of_Group_Customer_Group;

ALTER TABLE MANAGE_EXPENSE DROP CONSTRAINT FK_Of_Group_Voucher;
ALTER TABLE MANAGE_EXPENSE DROP CONSTRAINT FK_Of_Group_Customer_Group;

ALTER TABLE EXPENSE_RECEIPT DROP CONSTRAINT FK_Account_Person;
ALTER TABLE EXPENSE_RECEIPT DROP CONSTRAINT FK_Expense_Type;

ALTER TABLE APPLY_VOUCHER DROP CONSTRAINT fk_apply_voucher_vs_voucher;
ALTER TABLE APPLY_VOUCHER DROP CONSTRAINT fk_apply_voucher_vs_order;
ALTER TABLE RETURN_ORDER DROP CONSTRAINT fk_return_order_vs_order;
ALTER TABLE DELIVERY_INFO DROP CONSTRAINT fk_delivery_info_vs_order;


-- DROP TABLE
DROP TABLE IF EXISTS HANDLE;
DROP TABLE IF EXISTS GET_FEEDBACK;
DROP TABLE IF EXISTS PREPARE;
DROP TABLE IF EXISTS INCHARGE_OF;
DROP TABLE IF EXISTS INCLUDE_ITEM;
DROP TABLE IF EXISTS VOUCHER_VALID_PERIOD;
DROP TABLE IF EXISTS COMBINE;
DROP TABLE IF EXISTS PRODUCT_SET;
DROP TABLE IF EXISTS RECONCILE;
DROP TABLE IF EXISTS RECONCILIATION_FORM;
DROP TABLE IF EXISTS RETURN_ITEM;
DROP TABLE IF EXISTS RETURN_BILL;
DROP TABLE IF EXISTS IMPORT;
DROP TABLE IF EXISTS IMPORT_BILL;
DROP TABLE IF EXISTS INVENTORY_REPORT;
DROP TABLE IF EXISTS REVENUE_REPORT_BY_ITEM;
DROP TABLE IF EXISTS SUMMARIZE;
DROP TABLE IF EXISTS PLACE;
DROP TABLE IF EXISTS OF_GROUP;
DROP TABLE IF EXISTS RECEIVER_INFO;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS CUSTOMER_GROUP;
DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS SUPPLIER;
DROP TABLE IF EXISTS EXPENSE_TYPE;
DROP TABLE IF EXISTS EXPENSE_RECEIPT;
DROP TABLE IF EXISTS INCOME_TYPE;
DROP TABLE IF EXISTS INCOME_RECEIPT;
DROP TABLE IF EXISTS MANAGE_EXPENSE;
DROP TABLE IF EXISTS MANAGE_INCOME;
DROP TABLE IF EXISTS PROFIT_AND_LOSS_STATEMENT;
DROP TABLE IF EXISTS APPLY_VOUCHER;
DROP TABLE IF EXISTS RETURN_ORDER;
DROP TABLE IF EXISTS DELIVERY_INFO;
DROP TABLE IF EXISTS [ORDER];
DROP TABLE IF EXISTS SALARY;
DROP TABLE IF EXISTS WORK_ON;
DROP TABLE IF EXISTS SHIFT;
DROP TABLE IF EXISTS WORKING_PERIOD;
DROP TABLE IF EXISTS SUPERVISE;
DROP TABLE IF EXISTS SALES_EMPLOYEE;
DROP TABLE IF EXISTS PACKAGING_EMPLOYEE;
DROP TABLE IF EXISTS CUSTOMERSERVICE_EMPLOYEE;
DROP TABLE IF EXISTS ACCOUNTING_EMPLOYEE;
DROP TABLE IF EXISTS WAREHOUSE_EMPLOYEE;
DROP TABLE IF EXISTS EXPENSE_TYPE;
DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS VOUCHER;

-- Drop các sequence nếu có
DROP SEQUENCE IF EXISTS EmpID_Sequence;

SELECT table_name 
FROM information_schema.tables 
WHERE table_type = 'BASE TABLE' AND table_schema = 'dbo';

SELECT * FROM INCOME_RECEIPT
SELECT * FROM EXPENSE_RECEIPT
DELETE FROM EXPENSE_RECEIPT
WHERE Expense_ID > 5

-- Xóa Proceduce
GO
DROP PROCEDURE dbo.GetAllItems, dbo.GetItemById, AddItem, UpdateItem, GetAllReturnBills, AddReturnBill, GetReturnBillById, GetAllImportBills, GetImportBillById, UpdateImportBillState, ImportItemDetails, UpdateStockOnImport;
DROP PROCEDURE dbo.CreateOrderAndIncomeReceipt
DROP PROCEDURE dbo.InsertVoucher
DROP PROCEDURE dbo.GetAccountById, dbo.GetAllAccount
DROP PROCEDURE dbo.UpdateAccount
DROP PROCEDURE dbo.AssignShiftsForNextWeek
DROP PROCEDURE IF EXISTS RankAndAssignEmployeesToShifts;
DROP PROCEDURE IF EXISTS GetInsufficientShifts;
DROP PROCEDURE IF EXISTS GetEmployeesWithInsufficientShifts;
